Repository codefordallas/codefordallas.github.io, pull requests merged in 2023-10, with the labels that each got.

#49 Add ci
  .github/workflows/ci.yaml
  .gitignore
  package-lock.json
Labels: enhancement, requirements, automated testing, Not Approved - Changes Requested

#60 Issue58 doc4 formatting add
  docs/Linting_Prettier.md
Labels: enhancement, documentation, requirements

#55 explanation of proposed CI YAML file
  docs/CI_Explainer.md
Labels: enhancement, documentation
